# -- Site Configuration --

theme = "congo"

# baseURL = "https://joshuaknipe.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 25

[outputs]
  home = ["HTML", "RSS", "JSON"]

googleAnalytics = "G-XCWTR5DE5E"
