# -- Site Configuration --

# baseURL = "https://joshuaknipe.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 20

[outputs]
  home = ["HTML", "RSS", "JSON"]


googleAnalytics = "G-XCWTR5DE5E"
